require('./null');
require('./boolean');
require('./number');
require('./string');
require('./date');
require('./regexp');
require('./error');
require('./function');
require('./level-array');
require('./level-object');
require('./array');
require('./array-loop');
require('./object-simple');
require('./object-instance');
require('./object-loop');
require('./object-accessor');
require('./object-data');
require('./object-extensions');

console.log('test ok');
